export { CardDesignerTab } from './CardDesignerTab'
export { DesignerCanvas } from './DesignerCanvas'
export { DesignerToolbar } from './DesignerToolbar'
export { PropertiesPanel } from './PropertiesPanel'
export { useFabricCanvas } from './hooks/useFabricCanvas'
export { useDesignerHistory } from './hooks/useDesignerHistory'
export { fabricCanvasToSvg, generateSvgFromCanvasData, extractFieldsFromCanvasSvg } from './utils/fabricToSvg'
export { generateBarcodeDataUrl, generateBarcodePreview, validateBarcodeText, type BarcodeType } from './utils/barcodeGenerator'
export * from './types'
