#!/usr/bin/env node
/**
 * Rebuild the card templates in this folder from the designers' artboards.
 *
 *   node templates/build.mjs --artboard unbc=path/to/unbc-artboard.svg \
 *                            --artboard northern-health=path/to/nh-artboard.svg \
 *                            [--previews out/dir]
 *
 * Each sources/*.json names an artboard, the designs cut from it, and for each
 * design the variants (one card on the artboard each) plus a recipe saying
 * which drawn things are fields. Output goes to <family>/<design>/<variant>.svg.
 *
 * The artboards themselves are not kept in the repository: they are large,
 * carry sample photos, and are the designers' working files. Only the recipes
 * and their output are.
 *
 * Needs Playwright with Chromium (see tools/browser.mjs).
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { openBrowser, splitAndClean, applyRecipe, renderPng } from './tools/browser.mjs'

const ROOT = path.dirname(fileURLToPath(import.meta.url))

const artboards = {}
let previews = null
const args = process.argv.slice(2)
for (let i = 0; i < args.length; i += 1) {
  if (args[i] === '--artboard') {
    const [key, ...rest] = args[++i].split('=')
    artboards[key] = path.resolve(rest.join('='))
  } else if (args[i] === '--previews') {
    previews = path.resolve(args[++i])
  }
}

const sources = fs
  .readdirSync(path.join(ROOT, 'sources'))
  .filter((file) => file.endsWith('.json'))
  .map((file) => JSON.parse(fs.readFileSync(path.join(ROOT, 'sources', file), 'utf8')))

const browser = await openBrowser()
let problems = 0
try {
  for (const source of sources) {
    const artboard = artboards[source.artboard]
    if (!artboard) {
      console.log(`skip ${source.family}: no --artboard ${source.artboard}=…`)
      continue
    }
    console.log(`${source.family}: splitting ${path.basename(artboard)}`)
    const cards = new Map((await splitAndClean(browser, artboard, source.split ?? {})).map((card) => [card.id, card]))

    for (const design of source.designs) {
      const dir = path.join(ROOT, source.family, design.slug)
      fs.mkdirSync(dir, { recursive: true })
      for (const variant of design.variants) {
        const card = cards.get(variant.card)
        if (!card) {
          console.error(`  ${design.slug}/${variant.slug}: no ${variant.card} on the artboard`)
          problems += 1
          continue
        }
        const recipe = variant.recipe ?? design.recipe ?? {}
        const { svg, report } = await applyRecipe(browser, card.svg, recipe)
        const file = path.join(dir, `${variant.slug}.svg`)
        const header = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- ${design.name}: ${variant.name}. Generated by templates/build.mjs; edit sources/${source.family}.json, not this file. -->\n`
        fs.writeFileSync(file, header + svg + '\n')
        const note = report.length ? `  ⚠ ${report.join('; ')}` : ''
        if (report.length) problems += 1
        console.log(`  ${design.slug}/${variant.slug}.svg  ${(svg.length / 1024).toFixed(0)} KB${note}`)
        if (previews) {
          fs.mkdirSync(previews, { recursive: true })
          await renderPng(browser, file, path.join(previews, `${source.family}--${design.slug}--${variant.slug}.png`), 500)
        }
      }
    }
  }
} finally {
  await browser.close()
}
if (problems) {
  console.error(`${problems} card(s) need attention`)
  process.exitCode = 1
}
