/**
 * Layers that are part of the file but not part of the printed card.
 *
 * Designers need guides on the artboard — the bleed edge, the safe area, where
 * the lanyard slot will be punched — and they need fixed artwork (labels such as
 * "NAME" or "STUDENT NUMBER") that must not turn into editable fields. Both are
 * recognised by the layer's name, because a layer name is the one thing that
 * survives a round trip through Illustrator: it becomes the SVG `id`, while
 * custom `data-*` attributes are dropped on export.
 *
 *   guides, guide_bleed, guide-safe …   shown while editing, never printed
 *   punch, punch_slot_top_center …      where the card is punched; never printed,
 *                                       and drives the Punch guide
 *   static, artwork, static_labels …    fixed artwork; text inside is not a field
 *
 * `data-guide="true"` and `data-static="true"` are honoured as well, for files
 * written by hand or generated by this app.
 */

import type { PunchPosition, PunchShape } from './cardBlanks'

const GUIDE_ID = /^_?guides?(?:$|[_-])/i
const PUNCH_ID = /^_?punch(?:$|[_-])/i
const STATIC_ID = /^(?:static|artwork)(?:$|[_-])/i

export function isGuideLayerId(id: string | null | undefined): boolean {
  return Boolean(id && GUIDE_ID.test(id))
}

export function isPunchLayerId(id: string | null | undefined): boolean {
  return Boolean(id && PUNCH_ID.test(id))
}

export function isStaticLayerId(id: string | null | undefined): boolean {
  return Boolean(id && STATIC_ID.test(id))
}

function isNonPrinting(element: Element): boolean {
  const id = element.getAttribute('id')
  return element.getAttribute('data-guide') === 'true' || isGuideLayerId(id) || isPunchLayerId(id)
}

/**
 * Whether a node sits in a layer that cannot hold a field: a guide, the punch,
 * or fixed artwork.
 */
export function isInNonFieldLayer(node: Element): boolean {
  for (let current: Element | null = node; current; current = current.parentElement) {
    if (isNonPrinting(current)) return true
    if (current.getAttribute('data-static') === 'true' || isStaticLayerId(current.getAttribute('id'))) return true
  }
  return false
}

export type TemplatePunch = { position: Exclude<PunchPosition, 'none'>; shape: PunchShape }

/**
 * Read where the card is punched from a layer name such as
 * `punch_slot_top_center` or `punch-round-left-center`. A bare `punch` layer
 * is a slot at the top centre, which is what a lanyard badge almost always has.
 */
export function parsePunchLayerId(id: string): TemplatePunch | null {
  if (!isPunchLayerId(id)) return null
  // Illustrator appends "_1_" style suffixes to duplicate names; ignore digits.
  const tokens = id.toLowerCase().split(/[^a-z]+/).filter(Boolean)
  const has = (word: string) => tokens.includes(word)
  const shape: PunchShape = has('round') || has('hole') || has('circle') ? 'round' : 'slot'

  let position: TemplatePunch['position'] = 'top-center'
  if (has('bottom')) position = 'bottom-center'
  else if (has('top') && has('left')) position = 'top-left'
  else if (has('top') && has('right')) position = 'top-right'
  else if (has('left')) position = 'left-center'
  else if (has('right')) position = 'right-center'

  return { position, shape }
}

/** The punch a template declares, from its root attributes or a punch layer. */
export function findTemplatePunch(doc: Document): TemplatePunch | null {
  const root = doc.documentElement
  const declared = root?.getAttribute('data-punch')
  if (declared) {
    const parsed = parsePunchLayerId(`punch_${declared}_${root.getAttribute('data-punch-shape') ?? ''}`)
    if (parsed) return parsed
  }
  for (const element of Array.from(doc.querySelectorAll('[id]'))) {
    if (element.closest('defs')) continue
    const parsed = parsePunchLayerId(element.getAttribute('id') ?? '')
    if (parsed) return parsed
  }
  return null
}

/**
 * Take the non-printing layers out of a rendered card.
 *
 * The punch layer always goes: the preview draws the punch as an overlay, and on
 * the printed card it is a hole, not ink. Guides stay while editing so the
 * designer can see the bleed and safe area, and go when the card is printed.
 */
export function removeNonPrintingLayers(root: Element, { keepGuides }: { keepGuides: boolean }): void {
  const doomed = Array.from(root.querySelectorAll('*')).filter((element) => {
    if (element.closest('defs')) return false
    const id = element.getAttribute('id')
    if (isPunchLayerId(id)) return true
    if (keepGuides) return false
    return element.getAttribute('data-guide') === 'true' || isGuideLayerId(id)
  })
  for (const element of doomed) element.parentNode?.removeChild(element)
}
